### ISSUE TITLE
Add option to set banner

### ISSUE THREAD

**Issue by BlackusPL** [TheCuteOwl/discord-bot-animated-pfp#5]
Discord added ability for bots to have banner: https://twitter.com/DiscordPreviews/status/1768390153846825261
I found out that you can copy/paste `main.py` and change `"avatar"` to `"banner"` https://github.com/TheCuteOwl/discord-bot-animated-pfp/blob/f05363fbb60ebaf8b1b0604e89157e668a2e1636/main.py#L67

**Comment by TheCuteOwl** [comment]
Sure i'll add it
